language: elixir
elixir:
- 1.6
otp_release:
- 21.0
branches:
  only:
  - master
install:
- epmd -daemon
- mix local.hex --force
- mix local.rebar --force
script: make travis
before_script: make travis-init
deploy:
  skip_cleanup: true
  provider: script
  script: git clone https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG;
    cd $TRAVIS_REPO_SLUG; make travis-deploy
  on:
    branch: master
notifications:
  slack:
    secure: 
env:
  global:
    secure: dCIKVaQq5Jr2LASJ4UrrbiC7VQ7Y2s9og92VX+ZF9QJ1jgR3D1xxB+sdab/hnVnvDyS/GClkm1sr0FSJymNU0XGsCdpopZ8YosiaX13xHZGv8UuUikd26bSF10iL4JxgVCgoXtxoErytcR8MFOdQGHD7evhQVhmHFLOMArxfNa7ueRzelZKTkrIMxyHXO+FG7S3funBkMfTB+RU+fre9Rj709/urGiYMOF4BwLWQik0A2JCS7hzwkeUDXxe6CyWPRN18zDePr4SlOuTa4gsOhOUl7XH8fHzk8nqOC/CuFTDuhflwm4F23ELMJOe15qDsKM52RheP6AHttB9h7XomCrp5ZdKsbEGtJGI+hSf8NcOnwJF/KKfYrVophzunhQ0ZqmjvnLZ140vGlsdd8NiW4sBs1WkE08vdpVx+tI0g/BtpS3+1rm8OdrnRVCW+D0h1bkWWeqef7FnyTeJXM/BZnlHqOwW8FJTbEH103GLxdV8C6bYEp1SSj8dWgYAEFxLprjIBCCNsUM7jXPyj1hSzqoC6KReBPeuDvaljMSmiUJbL6FLWgmg0wy+VcbszAFbXQ702mQcq5BsaFo/JsGiQ2f+TNMRBNWa5Ir+QY8ksTq6qshRVj9gjenlX87JGOx5tFaGKw5i6n7j/fLwC3y5/R6UntXwmdwT9+F6yLe5kxOw=
